import assert from 'node:assert/strict';
const m=await import(new URL('../app/src/main/assets/app/profiles.js',import.meta.url));
const notes=[{id:'n1',note:'keep me',cfi:'epubcfi(/6/4!/4/2:0)'}];
const legacy={visualPresetVersion:3,profiles:{japanese:{fontSize:26,theme:'day',volume:false,margin:22},korean:{fontSize:25,theme:'night',lineHeight:1.7}},fonts:{korean:{id:'font1'}},books:{a:{mode:'japanese',notes,locations:{japanese:{cfi:'abc'},korean:{cfi:'def'}},location:{cfi:'abc'}}}};
m.migrateState(legacy);
assert.equal(legacy.profiles.bookwalker.fontSize,160);assert.equal(legacy.profiles.ridi.fontSize,8);
assert.equal(legacy.profiles.bookwalker.theme,'amber');assert.equal(legacy.profiles.ridi.theme,'night');
assert.equal(legacy.profiles.bookwalker.volume,false);assert.equal(legacy.profiles.bookwalker.margin,22);assert.equal(legacy.profiles.ridi.lineHeight,1.7);
assert.equal(legacy.books.a.mode,'bookwalker');assert.deepEqual(legacy.books.a.locations,{bookwalker:{cfi:'abc'},ridi:{cfi:'def'}});assert.deepEqual(legacy.books.a.notes,notes);assert.deepEqual(legacy.fonts.ridi,{id:'font1'});
const again=JSON.stringify(legacy);m.migrateState(legacy);assert.equal(JSON.stringify(legacy),again);
const oldNight=m.migrateState({profiles:{japanese:{fontSize:26,theme:'night'}}});assert.equal(oldNight.profiles.bookwalker.theme,'nightLight');
const previous=m.migrateState({readerSettingsVersion:1,profiles:{ridi:{topMargin:79,bottomMargin:28,fontSize:8}}});assert.equal(previous.profiles.ridi.topMargin,78);assert.equal(previous.profiles.ridi.bottomMargin,27);
const customMargins=m.migrateState({readerSettingsVersion:1,profiles:{ridi:{topMargin:65,bottomMargin:28}}});assert.equal(customMargins.profiles.ridi.topMargin,65);assert.equal(customMargins.profiles.ridi.bottomMargin,28);
for(const [theme] of m.themeOptions)assert.deepEqual(m.palette({preset:'bookwalker',theme}),m.palette({preset:'ridi',theme}));
assert.equal(m.ridiFontSize(8,412),25);assert.equal(m.ridiFontSize(8,600),30);assert.equal(m.ridiFontSize(8,720),32);
globalThis.window={screen:{width:412,height:915}};assert.equal(m.layoutPrefs(m.profiles[0].defaults).fontSize,160);assert.equal(m.layoutPrefs(m.profiles[1].defaults).fontSize,25);
window.screen={width:915,height:412};assert.equal(m.layoutPrefs(m.profiles[1].defaults).fontSize,25);
const preset=m.profiles[1].defaults;
assert.equal(preset.font,'original');assert.equal(preset.originalLineHeight,true);assert.equal(preset.publisher,true);assert.equal(preset.align,'original');
const oldPreset={...preset,font:'sans',originalLineHeight:undefined,publisher:false,align:'start',theme:'night',margin:24,fontSize:9};
const updated=m.migrateState({readerSettingsVersion:2,profiles:{ridi:{...oldPreset}},books:{a:{notes}}});
assert.equal(updated.profiles.ridi.font,'original');assert.equal(updated.profiles.ridi.originalLineHeight,true);assert.equal(updated.profiles.ridi.publisher,true);
assert.equal(updated.profiles.ridi.theme,'night');assert.equal(updated.profiles.ridi.margin,24);assert.equal(updated.profiles.ridi.fontSize,9);assert.deepEqual(updated.books.a.notes,notes);
const manual={...oldPreset,font:'ridi',lineHeight:1.8,spacing:.5,align:'justify'};
const preserved=m.migrateState({readerSettingsVersion:2,profiles:{ridi:manual}}).profiles.ridi;
assert.equal(preserved.font,'ridi');assert.equal(preserved.lineHeight,1.8);assert.equal(preserved.spacing,.5);assert.equal(preserved.align,'justify');assert.equal(preserved.publisher,false);assert.equal(preserved.originalLineHeight,false);
const stable=JSON.stringify(updated);m.migrateState(updated);assert.equal(JSON.stringify(updated),stable);
const thai=m.profiles.find(p=>p.id==='ridi-thai');
assert.equal(thai.engine,'ridi');assert.equal(thai.lang,'th');assert.equal(thai.defaults.font,'garuda');
const existing={readerSettingsVersion:3,profiles:{ridi:{...preset,fontSize:10,theme:'night'},bookwalker:{...m.profiles[0].defaults,fontSize:180}},books:{a:{mode:'ridi',notes,location:{cfi:'same-position'}}},fonts:{ridi:{id:'custom-font'}}};
const prior=structuredClone(existing);m.migrateState(existing);
assert.deepEqual(existing.profiles.ridi,prior.profiles.ridi);assert.deepEqual(existing.profiles.bookwalker,prior.profiles.bookwalker);
assert.deepEqual(existing.books,prior.books);assert.deepEqual(existing.fonts,prior.fonts);
existing.profiles['ridi-thai'].fontSize=32;existing.profiles['ridi-thai'].theme='green';m.migrateState(existing);
assert.equal(existing.profiles.ridi.fontSize,10);assert.equal(existing.profiles.ridi.theme,'night');
assert.equal(existing.profiles['ridi-thai'].fontSize,32);assert.equal(existing.profiles['ridi-thai'].theme,'green');
assert.equal(m.layoutPrefs(thai.defaults).fontSize,28);
for(const [theme] of m.themeOptions)assert.deepEqual(m.palette({preset:'ridi-thai',theme}),m.palette({preset:'ridi',theme}));
assert.match(m.contentCSS(thai.defaults),/font-family:'Garuda',sans-serif!important/);
assert.doesNotMatch(m.contentCSS(preset),/font-family:Garuda/);
console.log('PASS reader IDs, unit migration, custom settings, notes/positions/fonts preservation, idempotence, all shared palettes, RIDI phone/tablet sizes and orientation stability');
console.log('PASS Thai profile settings isolation, migration, shared themes and independent font scale');
